variable "resource_group_name" {
  type        = string
  description = "Name of the resource group where key-vault resources will be created"
}

variable "sql_admin_password" {
  type        = string
  description = "SQL admin password generated by the database module, to be stored as a Key Vault secret."
  sensitive = true
}

variable "aks_principal_id" {
  type        = string
  description = "Principal ID of the AKS cluster's managed identity, granted access to read secrets from this Key Vault"
}